const listaCompletaCID = [
  // --- SINTOMAS GERAIS E INESPECÍFICOS ---
  "R53.81 - Mal-estar geral",
  "R53.83 - Fadiga",
  "R05 - Tosse",
  "R06.0 - Dispneia",
  "R06.02 - Falta de ar",
  "R07.9 - Dor no peito, não especificada",
  "R10.9 - Dor abdominal, não especificada",
  "R11.2 - Náuseas e vómitos, não especificados",
  "R13.10 - Disfagia, não especificada",
  "R19.7 - Diarreia, não especificada",
  "R19.4 - Alteração do hábito intestinal",
  "R31.9 - Hematúria não especificada",
  "R32 - Incontinência urinária não especificada",
  "R33.9 - Retenção urinária",
  "R42 - Tontura e instabilidade",
  "R51 - Cefaleia",
  "R55 - Síncope e colapso",
  "R59.0 - Adenomegalia localizada",
  "R59.1 - Adenomegalia generalizada",
  "R63.4 - Perda de peso anormal",

  // --- ACHADOS ANORMAIS EM IMAGEM ---
  "R91.1 - Nódulo pulmonar solitário",
  "R91.8 - Outro achado pulmonar inespecífico",
  "R92.2 - Mamografia inconclusiva",
  "R93.0 - Achados anormais do crânio e cabeça",
  "R93.1 - Achados anormais do coração e circulação",
  "R93.2 - Achados anormais do fígado e vias biliares",
  "R93.3 - Achados anormais do trato gastrointestinal",
  "R93.4 - Achados anormais do trato geniturinário",
  "R93.5 - Achados anormais do abdómen/retroperitoneu",
  "R93.6 - Achados anormais dos membros",
  "R93.7 - Achados anormais do sistema músculo-esquelético",
  "R93.8 - Outros achados anormais em imagem",
  "R93.89 - Achados anormais em outros locais especificados",

  // --- NEUROLOGIA E CABEÇA/PESCOÇO ---
  "F03 - Demência não especificada",
  "G30.9 - Doença de Alzheimer, não especificada",
  "G35 - Esclerose múltipla",
  "G40.9 - Epilepsia, não especificada",
  "G43.9 - Enxaqueca, não especificada",
  "G51.0 - Paralisia de Bell",
  "I61.9 - Hemorragia intracerebral, não especificada",
  "I63.9 - Enfarte cerebral, não especificado",
  "I64 - AVC, não especificado",
  "J01.9 - Sinusite aguda, não especificada",
  "J32.9 - Sinusite crónica, não especificada",
  "H66.9 - Otite média, não especificada",

  // --- COLUNA VERTEBRAL ---
  "M41.9 - Escoliose, não especificada",
  "M47.9 - Espondilose, não especificada",
  "M50.2 - Outro deslocamento de disco cervical",
  "M51.2 - Outro deslocamento de disco intervertebral",
  "M54.2 - Cervicalgia",
  "M54.3 - Ciática",
  "M54.4 - Lumbago com ciática",
  "M54.5 - Dor lombar baixa",
  "Q76.2 - Espondilolistese congénita",

  // --- OSTEOMUSCULAR E ARTICULAÇÕES ---
  "M06.9 - Artrite reumatoide, não especificada",
  "M16.9 - Coxartrose não especificada",
  "M17.9 - Gonartrose não especificada",
  "M19.9 - Artrose não especificada",
  "M23.2 - Transtorno do menisco por lesão antiga",
  "M25.5 - Dor articular",
  "M65.9 - Sinovite e tenossinovite, não especificadas",
  "M75.1 - Síndrome do manguito rotador",
  "M75.4 - Síndrome de impacto do ombro",
  "M77.9 - Entesopatia, não especificada",
  "M79.1 - Mialgia",
  "M79.6 - Dor num membro",
  "M81.9 - Osteoporose, não especificada",

  // --- TRAUMA E FRATURAS ---
  "S00.9 - Traumatismo superficial da cabeça, não especificado",
  "S02.9 - Fratura do crânio e dos ossos da face, não especificada",
  "S06.9 - Traumatismo intracraniano, não especificado",
  "S12.9 - Fratura do pescoço, não especificada",
  "S22.0 - Fratura de vértebra torácica",
  "S22.3 - Fratura de costela",
  "S32.0 - Fratura de vértebra lombar",
  "S32.1 - Fratura do sacro",
  "S32.2 - Fratura do cóccix",
  "S32.4 - Fratura do acetábulo",
  "S32.5 - Fratura do púbis",
  "S32.7 - Fraturas múltiplas da coluna lombar e da pelve",
  "S42.2 - Fratura da extremidade superior do úmero",
  "S52.5 - Fratura da extremidade inferior do rádio",
  "S62.8 - Fratura de outros ossos da mão e do punho",
  "S72.0 - Fratura do colo do fémur",
  "S72.1 - Fratura pertrocantérica",
  "S82.0 - Fratura da rótula",
  "S82.8 - Fratura de outras partes da perna",
  "S93.4 - Entorse e distensão do tornozelo",

  // --- TÓRAX E RESPIRATÓRIO ---
  "J18.9 - Pneumonia, não especificada",
  "J20.9 - Bronquite aguda, não especificada",
  "J44.9 - DPOC, não especificada",
  "J45.9 - Asma, não especificada",
  "J90 - Derrame pleural",
  "I26.9 - Embolia pulmonar sem menção de cor pulmonale agudo",
  "J84.9 - Doença pulmonar intersticial, não especificada",

  // --- ABDÓMEN E GASTROINTESTINAL ---
  "K35.8 - Apendicite aguda, outras e não especificadas",
  "K40.9 - Hérnia inguinal unilateral ou não especificada",
  "K42.9 - Hérnia umbilical sem obstrução ou gangrena",
  "K43.9 - Hérnia abdominal, não especificada",
  "K56.6 - Obstrução intestinal, não especificada",
  "K57.9 - Doença diverticular do intestino, não especificada",
  "K74.6 - Cirrose hepática, não especificada",
  "K76.0 - Esteatose hepática",
  "K80.2 - Colelitíase sem colecistite",
  "K81.9 - Colecistite, não especificada",
  "K85.9 - Pancreatite aguda, não especificada",

  // --- PÉLVICA, UROLÓGICA E GINECOLÓGICA ---
  "N13.3 - Hidronefrose, não especificada",
  "N17.9 - Insuficiência renal aguda, não especificada",
  "N18.9 - Doença renal crónica, não especificada",
  "N20.0 - Cálculo renal",
  "N20.1 - Cálculo ureteral",
  "N20.2 - Cálculo renal com cálculo ureteral",
  "N20.9 - Litíase urinária, não especificada",
  "N21.0 - Cálculo vesical",
  "N23 - Cólica nefrética",
  "N28.1 - Cisto renal adquirido",
  "N28.9 - Transtorno renal e ureteral, não especificado",
  "N39.0 - Infeção urinária, não especificada",
  "Q61.9 - Doença cística do rim, não especificada",
  "N40 - Hiperplasia benigna da próstata",
  "N41.9 - Prostatite, não especificada",
  "N43.3 - Hidrocele, não especificado",
  "N44.9 - Torção do testículo e epidídimo",
  "N45.9 - Orquite/epididimite, não especificada",
  "N47 - Prepúcio redundante, fimose e parafimose",
  "N60.9 - Doença mamária benigna, não especificada",
  "N63 - Nódulo mamário não especificado",
  "N70.9 - Salpingite e ooforite, não especificadas",
  "N73.9 - Doença inflamatória pélvica feminina, não especificada",
  "N80.9 - Endometriose, não especificada",
  "N81.9 - Prolapso genital feminino, não especificado",
  "N83.2 - Cisto ovariano, outros e não especificados",
  "N84.0 - Pólipo do corpo do útero",
  "N85.0 - Hiperplasia glandular do endométrio",
  "N92.6 - Menstruação irregular, não especificada",
  "N93.9 - Sangramento uterino e vaginal anormal, não especificado",
  "N94.6 - Dismenorreia não especificada",
  "D25.9 - Leiomioma do útero, não especificado",
  "O00.9 - Gravidez ectópica, não especificada",

  // --- VASCULAR E CARDIO ---
  "I50.9 - Insuficiência cardíaca, não especificada",
  "I70.9 - Aterosclerose, não especificada",
  "I71.9 - Aneurisma da aorta, não especificado",
  "I73.9 - Doença vascular periférica, não especificada",
  "I80.2 - Trombose venosa profunda dos membros inferiores",
  "I83.9 - Varizes dos membros inferiores, sem úlcera ou inflamação",

  // --- ENDÓCRINO E METABÓLICO ---
  "E04.1 - Nódulo tiroideu simples",
  "E04.9 - Bócio não tóxico, não especificado",
  "E11.9 - Diabetes mellitus tipo 2 sem complicações",
  "E78.0 - Hipercolesterolemia pura",
  "E79.0 - Hiperuricemia",

  // --- ONCOLOGIA ---
  "C18.9 - Neoplasia maligna do cólon, não especificada",
  "C22.9 - Neoplasia maligna do fígado, não especificada",
  "C25.9 - Neoplasia maligna do pâncreas, não especificada",
  "C34.9 - Neoplasia maligna dos brônquios ou pulmões, não especificada",
  "C50.9 - Neoplasia maligna da mama, não especificada",
  "C53.9 - Neoplasia maligna do colo do útero, não especificada",
  "C61 - Neoplasia maligna da próstata",
  "C64 - Neoplasia maligna do rim, exceto pelve renal",
  "C71.9 - Neoplasia maligna do encéfalo, não especificada",
  "C73 - Neoplasia maligna da glândula tiroide",
  "C77.9 - Neoplasia maligna secundária e não especificada dos gânglios linfáticos",
  "C78.7 - Neoplasia maligna secundária do fígado",
  "C79.5 - Neoplasia maligna secundária dos ossos e da medula óssea",

  // --- ROTINA E RASTREIO ---
  "Z01.6 - Exame radiológico",
  "Z03.9 - Observação por suspeita de doença não especificada",
  "Z12.1 - Rastreio de neoplasia do intestino",
  "Z12.2 - Rastreio de neoplasia respiratória",
  "Z12.3 - Rastreio de neoplasia da mama",
  "Z12.31 - Rastreio mamográfico",
  "Z12.5 - Rastreio da próstata",
  "Z36.9 - Rastreio pré-natal, não especificado"
];
