// medicos.js
const listaCompletaMedicos = [
  "Abel Reina Rodriguez",
  "Abilene Vaz Sacramento",
  "Agostinho Napato",
  "Alberto Escalona Arzuaga",
  "Alemayehu Tegegne Tefera",
  "Alvaro Marcelino Cuenha",
  "Ana Maria Dias",
  "Bruna Daniela",
  "Bruna Komba",
  "Carlos Alberto Perez Alvarez",
  "Claudia Di Bella",
  "Claudia Ignoto",
  "Constantina Stela António",
  "Damaso Silvério",
  "Edgar Artahona Sosa",
  "Elizabeth Fernandez",
  "Ernesto Ulica",
  "Ester Catarina Freitas",
  "Estevão Claudio Rangel",
  "Estevão Muhongo",
  "Eyner Gonzalez",
  "Fernando Echevarria",
  "Fernando Flora",
  "Fernando Silva Coelho",
  "Filomena Coelho",
  "Gladys Garrido",
  "Gladys Lukeni Araujo",
  "Jandir Patrocínio",
  "Janete Cerqueira",
  "Jemima Patrocinio",
  "João Bilardo",
  "João Caiano",
  "Joice Dala",
  "Jose Luis Rodriguez",
  "José Hernandez",
  "Josemar Lima",
  "Juan Carlos Suarez",
  "Juliana Vanda de Macedo",
  "Lorette Cardona",
  "Maite Riveron Sainz",
  "Manuel Dolongo",
  "Marco António Tur",
  "Maria Elena Lopez de Isea",
  "Maria Esther Raola Sánchez",
  "Maria Sanchez",
  "Mauer Alexandre da Assunção",
  "Mauer Gonçalves",
  "Mircea Jawara de Rosa",
  "Mircea Jawara Neto",
  "Norvelis Duverger",
  "Olaida Montero",
  "Orestes Estevez",
  "Óscar Marquez",
  "Pedro Silva",
  "Roberto Ortiz",
  "Rodolfo Perez Gonzalez",
  "Rui Amilton Puna",
  "Sandra Martins",
  "Teresa Domingos",
  "Vagace Atilus",
  "Vanda Carapichoso",
  "Vera Fontes",
  "Virginia Santos",
  "Wilson José",
  "Wilson Laffita Labanino",
  "Wilson Rodrigo Jaime",
  "Wilson Teixeira",
  "Yadira Diaz",
  "Yaharina Labanino",
  "Yohanis Haile",
  "Yudelsy Quiala"
];
